## ERROR - Mayavi wont work because of this , probable install location issue == 
# RuntimeError: No tvtk.toolkits plugin found for toolkit null
#

## Python LIDAR data related Libs on PyPi
#
https://pypi.org/search/?q=lidar
https://pypi.org/project/libLAS/
https://pypi.org/project/sslam/
https://pypi.org/project/LiDARtoolkit/
https://github.com/jakarto3d/jakarto_datasets
https://github.com/jakarto3d/jakarto_datasets

##
# vtk - which is a dependency for Mayavi gets installed here == /usr/local/lib/python3.6/dist-packages/
# have copied it to the == anaconda3/envs/tensorflow_gpuenv
# 
$ /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/vtk
$ cp /usr/local/lib/python3.6/dist-packages/vtk /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/vtk
#
#

##
# traitsui -- has been there for a while - even before i installed Mayavi 
#
drwxr-sr-x 23 root staff  4096 Jun  5 23:28 pyface
drwxr-sr-x  2 root staff  4096 Jun  5 23:28 pyface-7.0.0.dist-info
drwxr-sr-x 12 root staff  4096 Jun  5 23:28 traitsui
drwxr-sr-x  2 root staff  4096 Jun  5 23:28 traitsui-7.0.0.dist-info
drwxr-sr-x 19 root staff  4096 Jun  5 23:28 apptools
drwxr-sr-x  2 root staff  4096 Jun  5 23:28 apptools-4.5.0.dist-info
drwxr-sr-x  7 root staff  4096 Jun  5 23:28 envisage
drwxr-sr-x  2 root staff  4096 Jun  5 23:28 envisage-4.9.2.dist-info
drwxr-sr-x 17 root staff  4096 Jun  5 23:28 numpy
drwxr-sr-x  2 root staff  4096 Jun  5 23:28 numpy.libs
drwxr-sr-x  2 root staff  4096 Jun  5 23:28 numpy-1.18.5.dist-info





## Termianl_Dumps
#
(base) dhankar@dhankar-1:~/_dc_all/tf$ conda activate tensorflow_gpuenv
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/tf$ pip install pykitti
Collecting pykitti
  Downloading pykitti-0.3.1-py2.py3-none-any.whl (13 kB)
Collecting pandas
  Downloading pandas-1.0.4-cp38-cp38-manylinux1_x86_64.whl (10.0 MB)
     |████████████████████████████████| 10.0 MB 1.4 MB/s 
Collecting Pillow
  Using cached Pillow-7.1.2-cp38-cp38-manylinux1_x86_64.whl (2.1 MB)
Requirement already satisfied: matplotlib in /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages (from pykitti) (3.2.1)
Requirement already satisfied: numpy in /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages (from pykitti) (1.18.1)
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 78.1 MB/s 
Requirement already satisfied: python-dateutil>=2.6.1 in /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages (from pandas->pykitti) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages (from matplotlib->pykitti) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages (from matplotlib->pykitti) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages (from matplotlib->pykitti) (0.10.0)
Requirement already satisfied: six>=1.5 in /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas->pykitti) (1.14.0)
Installing collected packages: pytz, pandas, Pillow, pykitti
Successfully installed Pillow-7.1.2 pandas-1.0.4 pykitti-0.3.1 pytz-2020.1
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/tf$ 
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/tf$ pip install mayavi
Collecting mayavi
  Downloading mayavi-4.7.1.tar.bz2 (7.0 MB)
     |████████████████████████████████| 7.0 MB 1.0 MB/s 
Collecting apptools
  Downloading apptools-4.5.0.tar.gz (297 kB)
     |████████████████████████████████| 297 kB 27.3 MB/s 
Collecting envisage
  Downloading envisage-4.9.2.tar.gz (518 kB)
     |████████████████████████████████| 518 kB 78.1 MB/s 
Requirement already satisfied: numpy in /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages (from mayavi) (1.18.1)
Collecting pyface>=6.1.1
  Downloading pyface-7.0.0.tar.gz (5.3 MB)
     |████████████████████████████████| 5.3 MB 26.2 MB/s 
Requirement already satisfied: pygments in /home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages (from mayavi) (2.6.1)
Collecting traits>=4.6.0
  Downloading traits-6.1.0.tar.gz (564 kB)
     |████████████████████████████████| 564 kB 26.2 MB/s 
Collecting traitsui>=6.0.0
  Downloading traitsui-7.0.0.tar.gz (5.2 MB)
     |████████████████████████████████| 5.2 MB 27.6 MB/s 
ERROR: Could not find a version that satisfies the requirement vtk (from mayavi) (from versions: none)
ERROR: No matching distribution found for vtk (from mayavi)
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/tf$ 
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/tf$ sudo apt-get install python-vtk
[sudo] password for dhankar: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-vtk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-vtk' has no installation candidate
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/tf$ 
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/tf$ sudo python3 -m pip install mayavi
WARNING: The directory '/home/dhankar/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting mayavi
  Downloading mayavi-4.7.1.tar.bz2 (7.0 MB)
     |████████████████████████████████| 7.0 MB 1.1 MB/s 
Collecting apptools
  Downloading apptools-4.5.0.tar.gz (297 kB)
     |████████████████████████████████| 297 kB 120.9 MB/s 
Collecting envisage
  Downloading envisage-4.9.2.tar.gz (518 kB)
     |████████████████████████████████| 518 kB 45.4 MB/s 
Collecting numpy
  Downloading numpy-1.18.5-cp36-cp36m-manylinux1_x86_64.whl (20.1 MB)
     |████████████████████████████████| 20.1 MB 37.1 MB/s 
Collecting pyface>=6.1.1
  Downloading pyface-7.0.0.tar.gz (5.3 MB)
     |████████████████████████████████| 5.3 MB 63.5 MB/s 
Collecting pygments
  Downloading Pygments-2.6.1-py3-none-any.whl (914 kB)
     |████████████████████████████████| 914 kB 125.5 MB/s 
Collecting traits>=4.6.0
  Downloading traits-6.1.0.tar.gz (564 kB)
     |████████████████████████████████| 564 kB 91.2 MB/s 
Collecting traitsui>=6.0.0
  Downloading traitsui-7.0.0.tar.gz (5.2 MB)
     |████████████████████████████████| 5.2 MB 30.4 MB/s 
Collecting vtk
  Downloading vtk-8.1.2-cp36-cp36m-manylinux1_x86_64.whl (48.9 MB)
     |████████████████████████████████| 48.9 MB 17.2 MB/s 
Collecting configobj
  Downloading configobj-5.0.6.tar.gz (33 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from apptools->mayavi) (1.11.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from envisage->mayavi) (39.0.1)
Building wheels for collected packages: mayavi, apptools, envisage, pyface, traits, traitsui, configobj
  Building wheel for mayavi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sbmx0tfn/mayavi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sbmx0tfn/mayavi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0uyaoynk
       cwd: /tmp/pip-install-sbmx0tfn/mayavi/
  Complete output (12 lines):
  ********************************************************************************
  
      Numpy is required to build Mayavi correctly, please install it first.
  
  ********************************************************************************
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-sbmx0tfn/mayavi/setup.py", line 406, in <module>
      raise RuntimeError(msg)
  RuntimeError:
      Numpy is required to build Mayavi correctly, please install it first.
  
  ----------------------------------------
  ERROR: Failed building wheel for mayavi
  Running setup.py clean for mayavi
  Building wheel for apptools (setup.py) ... done
  Created wheel for apptools: filename=apptools-4.5.0-py3-none-any.whl size=397647 sha256=f85d8fd4f7d553f3eb19a5af466ee467a4a22e0756c62ebfe4a1cde3a30cf5d4
  Stored in directory: /tmp/pip-ephem-wheel-cache-3ovxp6je/wheels/ff/b1/24/3e561302ea700a71351f9e216731a4ba5ceccfa309cb323d0d
  Building wheel for envisage (setup.py) ... done
  Created wheel for envisage: filename=envisage-4.9.2-py3-none-any.whl size=338101 sha256=4358d2234d2ee94c97abc8790081741c3379fc6a691501efdbb815697d8404b0
  Stored in directory: /tmp/pip-ephem-wheel-cache-3ovxp6je/wheels/92/c5/09/c9f4df6137b6418c113bd9e000d1b51b1f539bb7d43421ef1b
  Building wheel for pyface (setup.py) ... done
  Created wheel for pyface: filename=pyface-7.0.0-py3-none-any.whl size=1075703 sha256=c352d4e63fcee1608ad3daf69eba42034df51c3a441c455b0be51f926552346f
  Stored in directory: /tmp/pip-ephem-wheel-cache-3ovxp6je/wheels/fb/f7/d3/7f4fb55b344468b70b02aacb1de18f46086316fb47208f05cc
  Building wheel for traits (setup.py) ... done
  Created wheel for traits: filename=traits-6.1.0-cp36-cp36m-linux_x86_64.whl size=530357 sha256=0a41c43517b708eff5553351b0de94c782917328b0aede8b10bb0661bf6af998
  Stored in directory: /tmp/pip-ephem-wheel-cache-3ovxp6je/wheels/8f/5c/29/beda9cca12edcd262eedbcca174355f36be0b82e3dc852692b
  Building wheel for traitsui (setup.py) ... done
  Created wheel for traitsui: filename=traitsui-7.0.0-py3-none-any.whl size=786558 sha256=3cc341cebd8632acb84ee7f32268236d096cc13a354ed79cd8d47b16619645cb
  Stored in directory: /tmp/pip-ephem-wheel-cache-3ovxp6je/wheels/fc/57/da/3f344a31636357a7286b691814c5e21cd56050e55dab45d6e5
  Building wheel for configobj (setup.py) ... done
  Created wheel for configobj: filename=configobj-5.0.6-py3-none-any.whl size=36364 sha256=e4f93910b040a5eb583e917a7e412aa86424be9468bd1effb8f9731a08a61500
  Stored in directory: /tmp/pip-ephem-wheel-cache-3ovxp6je/wheels/14/d5/8e/1a6dd2be7614b4a455867b3b5eb57054f278470a4c07564381
Successfully built apptools envisage pyface traits traitsui configobj
Failed to build mayavi
Installing collected packages: configobj, traits, pyface, traitsui, apptools, envisage, numpy, pygments, vtk, mayavi
    Running setup.py install for mayavi ... done
Successfully installed apptools-4.5.0 configobj-5.0.6 envisage-4.9.2 mayavi-4.7.1 numpy-1.18.5 pyface-7.0.0 pygments-2.6.1 traits-6.1.0 traitsui-7.0.0 vtk-8.1.2
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/tf$ 
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/tf$ 


## FOOBAR---- mayavi and VTK 

(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/lidar/semantic_kitti/semantic-kitti-api$ pip3 install vtk
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: vtk in /usr/local/lib/python3.6/dist-packages (8.1.2)
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/lidar/semantic_kitti/semantic-kitti-api$ cd /usr/local/lib/python3.6/dist-packages
(tensorflow_gpuenv) dhankar@dhankar-1:/usr/local/lib/python3.6/dist-packages$ ls -ltr

-rw-r--r--  1 root staff   675 Jun  5 23:28 vtkVersion.py
drwxr-sr-x  2 root staff  4096 Jun  5 23:28 __pycache__
drwxr-sr-x 11 root staff 20480 Jun  5 23:28 vtk
drwxr-sr-x  2 root staff  4096 Jun  5 23:28 vtk-8.1.2.dist-info
drwxr-sr-x 15 root staff  4096 Jun  5 23:29 mayavi
drwxr-sr-x 11 root staff  4096 Jun  5 23:29 tvtk
drwxr-sr-x  2 root staff  4096 Jun  5 23:29 mayavi-4.7.1.egg-info
(tensorflow_gpuenv) dhankar@dhankar-1:/usr/local/lib/python3.6/dist-packages$ python
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import mayavi
>>> import vtk
>>> 
>>> 
[1]+  Stopped                 python
(tensorflow_gpuenv) dhankar@dhankar-1:/usr/local/lib/python3.6/dist-packages$ 
(tensorflow_gpuenv) dhankar@dhankar-1:/usr/local/lib/python3.6/dist-packages$ cd -
/home/dhankar/_dc_all/lidar/semantic_kitti/semantic-kitti-api
(tensorflow_gpuenv) dhankar@dhankar-1:~/_dc_all/lidar/semantic_kitti/semantic-kitti-api$ 
#
#



##ERROR_DUMP --- probably need to file an issue with Mayavi == RuntimeError: No tvtk.toolkits plugin found for toolkit null
# Not sure if its same issue as this == https://github.com/enthought/mayavi/issues/652

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-053352eb1b10> in <module>
      1 # Plot using mayavi -Much faster and smoother than matplotlib
----> 2 import mayavi.mlab
      3 
      4 fig = mayavi.mlab.figure(bgcolor=(0, 0, 0), size=(640, 360))
      5 mayavi.mlab.points3d(

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/mayavi/mlab.py in <module>
     14 # Mayavi imports
     15 from mayavi.core.common import process_ui_events
---> 16 from mayavi.tools.camera import view, roll, yaw, pitch, move
     17 from mayavi.tools.figure import figure, clf, gcf, savefig, \
     18     draw, sync_camera, close, screenshot

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/mayavi/tools/camera.py in <module>
     22 # We can't use gcf, as it creates a circular import in camera management
     23 # routines.
---> 24 from .engine_manager import get_engine
     25 
     26 

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/mayavi/tools/engine_manager.py in <module>
     12 from mayavi.preferences.api import preference_manager
     13 from mayavi.core.registry import registry
---> 14 from mayavi.core.engine import Engine
     15 from mayavi.core.off_screen_engine import OffScreenEngine
     16 from mayavi.core.null_engine import NullEngine

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/mayavi/core/engine.py in <module>
     32 from mayavi.core.adder_node import AdderNode, SceneAdderNode
     33 from mayavi.preferences.api import preference_manager
---> 34 from mayavi.core.ui.mayavi_scene import viewer_factory
     35 
     36 

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/mayavi/core/ui/mayavi_scene.py in <module>
     10 
     11 # Enthought library imports
---> 12 from tvtk.tools.ivtk import IVTK
     13 from tvtk.pyface.api import DecoratedScene
     14 from traits.api import Callable

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/tvtk/tools/ivtk.py in <module>
     33 from pyface.api import SplitApplicationWindow, ApplicationWindow
     34 from pyface.api import SplitPanel
---> 35 from tvtk.pyface.api import Scene, DecoratedScene
     36 from pyface.action.api import Action, MenuBarManager,\
     37      MenuManager, Separator

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/tvtk/pyface/api.py in <module>
----> 1 from .decorated_scene import DecoratedScene
      2 from .scene import Scene

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/tvtk/pyface/decorated_scene.py in <module>
     10 
     11 # Import the toolkit specific version.
---> 12 from tvtk.pyface.toolkit import toolkit_object
     13 DecoratedScene = toolkit_object('decorated_scene:DecoratedScene')

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/tvtk/pyface/toolkit.py in <module>
      1 from pyface.base_toolkit import find_toolkit
      2 
----> 3 toolkit = toolkit_object = find_toolkit('tvtk.toolkits')

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/pyface/base_toolkit.py in find_toolkit(entry_point, toolkits, priorities)
    267     """
    268     if ETSConfig.toolkit:
--> 269         return import_toolkit(ETSConfig.toolkit, entry_point)
    270 
    271     entry_points = [

~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/pyface/base_toolkit.py in import_toolkit(toolkit_name, entry_point)
    213         msg = msg.format(entry_point, toolkit_name)
    214         logger.debug(msg)
--> 215         raise RuntimeError(msg)
    216     elif len(plugins) > 1:
    217         msg = "multiple %r plugins found for toolkit %r: %s"

RuntimeError: No tvtk.toolkits plugin found for toolkit null




##ERROR_DUMP --- Errors out in Jupyter also errors out in console / python prompt ..
(tensorflow_gpuenv) dhankar@dhankar-1:~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages$ 
(tensorflow_gpuenv) dhankar@dhankar-1:~/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages$ python
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import mayavi
>>> import vtk
>>> 
>>> from mayavi import mlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/mayavi/core/engine.py", line 34, in <module>
    from mayavi.core.ui.mayavi_scene import viewer_factory
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/mayavi/core/ui/mayavi_scene.py", line 12, in <module>
    from tvtk.tools.ivtk import IVTK
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/tvtk/tools/ivtk.py", line 35, in <module>
    from tvtk.pyface.api import Scene, DecoratedScene
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/tvtk/pyface/api.py", line 1, in <module>
    from .decorated_scene import DecoratedScene
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/tvtk/pyface/decorated_scene.py", line 12, in <module>
    from tvtk.pyface.toolkit import toolkit_object
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/tvtk/pyface/toolkit.py", line 3, in <module>
    toolkit = toolkit_object = find_toolkit('tvtk.toolkits')
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/pyface/base_toolkit.py", line 269, in find_toolkit
    return import_toolkit(ETSConfig.toolkit, entry_point)
  File "/home/dhankar/anaconda3/envs/tensorflow_gpuenv/lib/python3.8/site-packages/pyface/base_toolkit.py", line 215, in import_toolkit
    raise RuntimeError(msg)
RuntimeError: No tvtk.toolkits plugin found for toolkit null
>>> 



##### python-vtk

$ sudo apt-get install -y python-vtk
[sudo] password for dhankar: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-vtk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-vtk' has no installation candidate







## Code_Dump - not an error
#
"""
    Loads dataset labels also referred to as tracklets, saving them individually for each frame.

    Parameters
    ----------
    n_frames    : Number of frames in the dataset.
    xml_path    : Path to the tracklets XML.

    Returns
    -------
    Tuple of dictionaries with integer keys corresponding to absolute frame numbers and arrays as values. First array
    contains coordinates of bounding box vertices for each object in the frame, and the second array contains objects
    types as strings.
    """
    tracklets = xmlParser.parseXML(xml_path)


plt.savefig('test.pdf',quality=90) 

# Save the image in memory in PNG format
png1 = io.BytesIO()
plt.savefig(png1, format="png")

# Load this image into PIL
png2 = Image.open(png1)

# Save as TIFF
png2.save("3dPlot.tiff")
png1.close()



"""
, dpi=None, facecolor='w', edgecolor='w',
        orientation='portrait', papertype=None, format=None,
        transparent=False, bbox_inches=None, pad_inches=0.1,
        frameon=None, metadata=None
"""
